### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#1233] opened 2024-10-09 09:13 UTC
Hera supports 3.13 for the core features, but [cicd](https://github.com/argoproj-labs/hera/actions/runs/11251436076/job/31283410814?pr=1232) (`make test` specifically) is blocked by the tests for new decorators breaking - varname seems to have a compatibility issue, see https://github.com/pwwang/python-varname/issues/116

**Comment by pwwang** [comment] 2024-10-11 18:08
I am the author of varname. Posting some updates here.

I cloned the repo and ran the tests regarding varname with python 3.13. I can't reproduce the errors in the CI.
I will keep looking for the cause.

**Comment by pwwang** [comment] 2024-10-11 18:29
I found that this is caused by executing not pinned to `^2.1`. This should be fixed by varname v0.13.5

**Closed** 2024-10-14 10:52 UTC
Labels: type:dependency-upgrade
