### ISSUE TITLE
Script runner errors out with `AttributeError`

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera#799] opened 2023-10-04 13:43 UTC
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When trying to use the script runner option for creating scripts, I run into `AttributeError`. It is always searching for the function in `__main__` which I think is the issue, since I would assume it should be searching in the module that is being run. I am attaching the YAML as well with what I think is the offending line ` __main__:task_with_image_pull_policy`

_Error log if applicable_:
```
time="2023-10-04T13:21:45.972Z" level=info msg="capturing logs" argo=true
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 276, in <module>
    _run()
  File "/home/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 269, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/home/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 220, in _runner
    function = getattr(importlib.import_module(module), function_name)
AttributeError: module '__main__' has no attribute 'task_with_image_pull_policy'
time="2023-10-04T13:21:46.975Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from typing import List

from hera.workflows import (
    Parameter,
    Workflow,
    models as m,
    Script, script
)

from project.config import WORKFLOW_CONFIG
from hera.shared import global_config

global_config.set_class_defaults(Script, constructor="runner")
global_config.experimental_features["script_runner"] = True
global_config.image = f"{WORKFLOW_CONFIG.aws_ecr}"
global_config.script_command = ["python3"]


def _parameters_for_workflow() -> List[Parameter]:
    return [
        Parameter(name="logs-directory", value=WORKFLOW_CONFIG.logs_directory),
    ]


@script(image_pull_policy=m.ImagePullPolicy.always)
def task_with_image_pull_policy():
    print("ok")


with Workflow(generate_name="script-with-image-pull-policy-", entrypoint="task-with-image-pull-policy",
              arguments=_parameters_for_workflow()) as w:
    task_with_image_pull_policy()

w.create()
```

**YAML**
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: script-with-image-pull-policy-
spec:
  arguments:
    parameters:
    - name: logs-directory
      value: /tmp/logs
  entrypoint: task-with-image-pull-policy
  templates:
  - name: task-with-image-pull-policy
    script:
      args:
      - -m
      - hera.workflows.runner
      - -e
      - __main__:task_with_image_pull_policy
      command:
      - python3
      image: ***.ecr.eu-central-1.amazonaws.com/pipe-src:development-singh-hera-script
      imagePullPolicy: Always
      source: '{{inputs.parameters}}'
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

**Environment**
 - OS: [Kubuntu]
 - Browser: [firefox]
 - Version of Hera: [5.7,1]
 - Version of Argo: [e.g. 3.4.4]

**Comment by vikramsg** [comment] 2023-10-04 14:03
Ok, I have more insight on this and maybe this is related to https://github.com/argoproj-labs/hera/issues/573

If I invoke the script containing the function directly, that is, `python3 -m script` then the module `https://github.com/argoproj-labs/hera/blob/c8cbf0c7a676de57469ca3d6aeacde7a5e84f8b7/src/hera/workflows/script.py#L732` detected is always going to be `__main__`. The hack is to always call it from another script. 

However, I think, the handling could be changed so that we don't have to do this. Does that make sense?

**Comment by elliotgunton** [comment] 2023-10-04 16:19
Yes, looks to be a case of checking `if __module__ == "__main__"` then we want the `values["source"]` directly, [here](https://github.com/argoproj-labs/hera/blob/c8cbf0c7a676de57469ca3d6aeacde7a5e84f8b7/src/hera/workflows/script.py#L732)

**Comment by vikramsg** [comment] 2023-10-05 07:43
I can have a go at a PR. Would that be of interest? Any ideas on what tests I should target. I don't think there are existing tests that handle this particular issue.

**Comment by elliotgunton** [comment] 2024-02-20 16:22
Closing this as a dupe of #573. Contributions are welcome but I'm not actually sure how to fix this yet after a brief look into it.

**Closed by elliotgunton** 2024-02-20 16:22 UTC
