### ISSUE TITLE
 make test is broken with cappa dependency 

### ISSUE THREAD

**Issue by paravatha** [argoproj-labs/hera#907] opened 2023-12-23 23:50 UTC
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [ ] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [x] other: 

<h2>Bug report</h2>

**Describe the bug**
` make lint test `and `make test `are throwing this error

I tried with python 3..8 and python 3.11, same issue occurs for both python versions

_Error log if applicable_:
```
397 files left unchanged
src/hera/_cli/base.py:7: error: Cannot find implementation or library stub for module named "cappa"  [import]
src/hera/__main__.py:15: error: Cannot find implementation or library stub for module named "cappa"  [import]
src/hera/__main__.py:15: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 113 source files)
make: *** [lint] Error 1
```

**Environment**
- Python Version: 3.11 and 3.8

**Additional context**

**Comment by elliotgunton** [comment] 2023-12-28 09:42
Hey @paravatha - could you rerun `make install`? I think you just need to refresh your python environment! This was fixed in #905 [here](https://github.com/argoproj-labs/hera/pull/905/commits/d2197055abc2239896c118afd9a62d1ccac3af77). Closing as fixed (reopen if a new environment doesn't help!) - I couldn't reproduce in a fresh environment:

```console
$ make install
Creating virtualenv hera-ZUOVT4Nk-py3.10 in /home/codespace/.cache/pypoetry/virtualenvs
...

Installing the current project: hera (0.0.0-dev)
$ make lint
396 files left unchanged
Success: no issues found in 113 source files
```

**Closed by elliotgunton** 2023-12-28 09:42 UTC
